name: EC2Workflow

on:
  push:
    branches:
      - Feature-deploy-in-AWS
    paths:
      - "server/**"

defaults:
  run:
    working-directory: "server"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Create private key
        run: echo "${{ secrets.VIDEO_STORAGE_PRIVATE_KEY}}" > videoStorage.pem

      - name: Connect to EC2
        run: |
          chmod 400 videoStorage.pem
          ssh -i videoStorage.pem -o StrictHostKeyChecking=no ec2-user@ec2-34-241-38-70.eu-west-1.compute.amazonaws.com << EOF
              cd video-storage-app
              git pull
              cd server
              npm install
              NODE_ENV=aws pm2 restart server.js
          EOF
